# Site meta data
email: example@example.org
url: "http://andeon.github.io"

# not used by plugin but by liquid template
languages: ['en', 'de']

# Build settings
markdown: kramdown

gems:
- jekyll-sitemap
- jekyll-language-plugin

language_data: data.lang.%%
language_includes_dir: _i18n
